"""Add cafe

Revision ID: 076c8ab3ffa6
Revises: 
Create Date: 2021-11-15 21:09:05.258906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076c8ab3ffa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('open_hour', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('kakao_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cafes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafes')
    # ### end Alembic commands ###
